### ISSUE TITLE
Make android buidls fail, if some error occurs in checkstyle

### ISSUE THREAD

**Issue by TheReprator** [pwittchen/android-quality-starter#1]
Currently, i am able to make the builds, even if there is some error found by checkstyle. So basically i wanted to abort the builds if there is any error reproted by checkstyle with android studio.

**Comment by pwittchen** [comment]
Hi,

Please check if your checkstyle is consistent with [config/quality/checkstyle/checkstyle.xml](https://github.com/pwittchen/android-quality-starter/blob/master/config/quality/checkstyle/checkstyle.xml) and if suppressions in [config/quality/checkstyle/suppressions.xml](https://github.com/pwittchen/android-quality-starter/blob/master/config/quality/checkstyle/suppressions.xml) files are consistent with your suppressions. You can adjust these files to your needs. E.g. if you want to have more strict or liberal checkstyle rules. I think you should add more rules to the `checkstyle.xml` if you want the build to fail, but it's not failing.

Regards,
Piotr

**Comment by TheReprator** [comment]
AnyWay, i found answer,

```groovy
apply plugin: 'checkstyle'
preBuild.dependsOn('checkstyle')
assemble.dependsOn('lint')
check.dependsOn('checkstyle')
configurations {
    checksytleOverride
} 
```

Just paste the above code in app level `build.gradle`, it will stop the build from being generated. I request you to kindly add this line in your readme.

**Comment by pwittchen** [comment]
When you go to the [quality.gradle](https://github.com/pwittchen/android-quality-starter/blob/master/config/quality.gradle) file, you can notice that checkstyle is applied there and
```
check.dependsOn 'checkstyle', 'findbugs', 'pmd', 'lint'
```

In the `README.md` it's written that you need to add line:

```
apply from: '../config/quality.gradle'
```

to the `build.gradle` file. When you are done, you need to execute:

```
./gradlew check
```

and it should work.

It's strange that it didn't worked for you, but it's great you solved the problem :).

**Comment by TheReprator** [comment]
It worked but it didn't abort the builds from getting generated i have to manually check the checkstyle violation error by "./gradlew check" from terminal
